const eyes = ["amber", "amethyst", "apricot", "aqua", "aquamarine", "azure",  
    "baby blue", "beige", "black", "blue", "blue-green", "blue-violet", "blush", "bronze", "brown", "burgundy", "byzantium",  
    "carmine", "cerise", "cerulean", "champagne", "chartreuse", "chocolate", "cobalt", "coffee", "copper", "coral", "crimson", "crystal", "cyan", 
    "dawn", 
    "earth", "electric blue", "emerald", 
    "glacial", "gold", "gray", "green", 
    "hazel", "hetero black/white", "hetero blue/brown", "hetero blue/green", "hetero brown/green", 
    "ice", "indigo", 
    "jade", "jet", 
    "lavender", "lemon", "lilac", "lime", "lightning", 
    "magenta", "maroon", "mint", 
    "ochre", "olive", 
    "pink", "purple", 
    "red", "ruby", 
    "sapphire", "silver", 
    "tan", 
    "violet", 
    "white", 
    "yellow", ];

module.exports = eyes;