const pers = ["active", "admirable", "adventurous", "agreeable", "alert", "aspiring", "athletic", "attractive", "absentminded", "ambitious", "amusing", "abrupt", 
    "brilliant", "breezy", "busy", "blunt", 
    "calm", "capable", "caring", "charismatic", "charming", "cheerful", "clever", "compassionate", "confident", "considerate", "cooperative", "courageous", "creative", "curious", "casual", "competitive", "cute", "childish", "cruel", "critical", 
    "daring", "dedicated", "dignified", "disciplined", "dramatic", "deceptive", "determined", "dreamy", "dry", 
    "earnest", "efficient", "elegant", "empathetic", "energetic", "enthusiastic", "exciting", "earthy", "emotional", 
    "faithful", "firm", "forgiving", "friendly", "formal", 
    "generous", "gentle", "genuine", "goodnatured", 
    "hardworking", "healthy", "hearty", "helpful", "honest", "honourable", "humble", "humourous", 
    "imaginative", "impressive", "independent", "innovative", "insightful", "intelligent", "intuitive", "intense", 
    "kind", "knowledgeable", 
    "mature", "methodical", "modest", "maternal", "mellow", 
    "neat", 
    "observant", "optimistic", "organized", "obedient", "outspoken", "old-fashioned", "ordinary", 
    "passionate", "patient", "patriotic", "peaceful", "perceptive", "perfectionist", "persuasive", "playful", "popular", "practical", "precise", "protective", "proud", 
    "rational", "realistic", "relaxed", "reliable", "respectful", "responsible", "romantic", 
    "selfless", "sensitive", "sapphic", "simple", "skillful", "sociable", "sophisticated", "steady", "subtle", "sweet", "sympathetic", "sarcastic", "skeptical", "soft", "smooth", "solemn", "stern", "stoic", "stubborn", "surprising", 
    "tolerant", "trusting", "tough", 
    "understanding", 
    "vivacious", 
    "warm", "well-rounded", "wise", "witty", ];

module.exports = pers;