const mcBlock = ["acacia button", "acacia door", "acacia fence", "acacia fence gate", "acacia leaves", "acacia log", 
    "acacia planks", "acacia pressure plate", "acacia sapling", "acacia sign", "acacia slab", "acacia stairs", 
    "acacia trapdoor", "acacia wood", "activator rail", "air", "allium", "andesite", "andesite slab", "andesite stairs", 
    "andesite wall", "anvil", "azure bluet", 
    "bamboo", "bamboo sapling", "barrel", "barrier", "beacon", "bedrock", "bell", "birch button", "birch door", 
    "birch fence", "birch fence gate", "birch leaves", "birch log", "birch planks", "birch pressure plate", "birch sapling", 
    "birch sign", "birch slab", "birch stairs", "birch trapdoor", "birch wood", "black banner", "black bed", "black carpet", 
    "black concrete", "black concrete powder", "black glazed terracotta", "black shulker box", "black stained glass", 
    "black stained glass pane", "black terracotta", "black wool", "blast furnace", "blue banner", "blue bed", "blue carpet", 
    "blue concrete", "blue concrete powder", "blue glazed terracotta", "blue ice", "blue orchid", "blue shulker box", 
    "blue stained glass", "blue stained glass pane", "blue terracotta", "blue wool", "bone block", "bookshelf", 
    "brain coral", "brain coral", "brain coral fan", "brewing stand", "brick slab", "brick stairs", "brick wall", 
    "bricks", "brown banner", "brown bed", "brown carpet", "brown concrete", "brown concrete powder", 
    "brown glazed terracotta", "brown mushroom", "brown mushroom block", "brown shulker box", "brown stained glass", 
    "brown stained glass pane", "brown terracotta", "brown wool", "bubble column", "bubble coral", "bubble coral block", 
    "bubble coral fan", 
    "cactus", "cake", "campfire", "cartography table", "carved pumpkin", "cauldron", "chain command block", "chest", 
    "chipped anvil", "chiseled quartz block", "chiseled red sandstone", "chiseled sandstone", "chiseled stone bricks", 
    "chorus flower", "chorus plant", "clay", "coal block", "coal ore", "coarse dirt", "cobblestone", "cobblestone slab", 
    "cobblestone stairs", "cobblestone wall", "cobweb", "cocoa", "command block", "composter", "conduit", "cornflower", 
    "cracked stone bricks", "crafting table", "creeper head", "cut red sandstone", "cut red sandstone slab", 
    "cut sandstone", "cut sandstone slab", "cyan banner", "cyan bed", "cyan carpet", "cyan concrete", 
    "cyan concrete powder", "cyan glazed terracotta", "cyan wool", 
    "damaged anvil", "dandelion", "dark oak button", "dark oak door", "dark oak fence", "dark oak fence gate", 
    "dark oak leaves", "dark oak log", "dark oak planks", "dark oak pressure plate", "dark oak sapling", "dark oak sign", 
    "dark oak slab", "dark oak stairs", "dark oak trapdoor", "dark oak wood", "dark prismarine slab", 
    "dark prismarine stairs", "dark prismarine", "daylight detector", "dead brain coral block", "dead brain coral fan", 
    "dead brain coral", "dead bubble coral block", "dead bubble coral fan", "dead bubble coral", "dead bush", 
    "dead fire coral block", "dead fire coral fan", "dead fire coral", "dead horn coral block", "dead horn coral fan", 
    "dead horn coral", "dead tube coral block", "dead tube coral fan", "dead tube coral", "detector rail", "diamond block", 
    "diamond ore", "diorite slab", "diorite stairs", "diorite wall", "diorite", "dirt", "dispenser", "dragon egg", 
    "dragon head", "dried kelp block", "dropper", 
    "emerald block", "emerald ore", "enchanting table", "end portal frame", "end portal", "end rod", "end stone brick slab", 
    "end stone brick stairs", "end stone brick wall", "end stone bricks", "end stone", "ender chest", 
    "farmland", "fern", "fire coral block", "fire coral fan", "fire coral", "fire", "fletching table", "flower pot", 
    "frosted ice", "furnace", 
    "glass pane", "glass", "glowstone", "gold block", "gold ore", "granite slab", "granite stairs", "granite wall", 
    "granite", "grass block", "grass path", "grass", "gravel", "gray banner", "gray bed", "gray carpet", 
    "gray concrete powder", "gray concrete", "gray glazed terracotta", "gray shulker box", "gray stained glass pane", 
    "gray stained glass", "gray terracotta", "gray wool", "green banner", "green bed", "green carpet", 
    "green concrete powder", "green concrete", "green glazed terracotta", "green shulker box", "green stained glass pane", 
    "green stained glass", "green terracotta", "green wall banner", "green wool", "grindstone", 
    "hay bale", "heavy weighted pressure plate", "hopper", "horn coral block", "horn coral fan", "horn coral", 
    "ice", "iron bars", "iron block", "iron ore", "iron trapdoor", 
    "jack o lantern", "jigsaw block", "jukebox", "jungle button", "jungle door", "jungle fence gate", "jungle fence", 
    "jungle leaves", "jungle log", "jungle planks", "jungle pressure plate", "jungle sapling", "jungle slab", 
    "jungle stairs", "jungle sign", "jungle trapdoor", "jungle wood", 
    "kelp", "kelp plant", 
    "ladder", "lantern", "lapis lazuli block", "lapis lazuli ore", "large fern", "lava", "lectern", "lever", 
    "light blue banner", "light blue bed", "light blue carpet", "light blue concrete powder", "light blue concrete", 
    "light blue glazed terracotta", "light blue shulker box", "light blue stained glass pane", "light blue stained glasses", 
    "light blue terracotta", "light blue wool", "light gray banner", "light gray bed", "light gray carpet", 
    "light gray concrete powder", "light gray concrete", "light gray glazed terracotta", "light gray shulker box", 
    "light gray stained glass pane", "light gray stained glass", "light gray terracotta", "light gray wool", 
    "light weighted pressure plate", "lilac", "lily of the valley", "lily pad", "lime banner", "lime bed", "lime carpet", 
    "lime concrete powder", "lime concrete", "lime glazed terracotta", "lime shulker box", "lime stained glass pane", 
    "lime stained glass", "lime terracotta", "lime wool", "loom", 
    "magenta banner", "magenta bed", "magenta carpet", "magenta concrete powder", "magenta concrete", 
    "magenta glazed terracotta", "magenta shulker box", "magenta stained glass pane", "magenta stained glass", 
    "magenta terracotta", "magenta wool", "magma block", "melon block", "mossy cobblestone slabs", 
    "mossy cobblestone stairs", "mossy cobblestone wall", "mossy cobblestone", "mossy stone brick slab", 
    "mossy stone brick stairs", "mossy stone brick walls", "mossy stone bricks", "mushroom stem", "mycelium", 
    "nether brick fence", "nether brick slab", "nether brick stairs", "nether brick wall", "nether bricks", 
    "nether quartz ore", "nether wart block", "nether wart", "netherrack", "note block", 
    "oak button", "oak door", "oak fence gate", "oak fence", "oak log", "oak planks", "oak pressure plate", 
    "oak sapling", "oak slab", "oak stairs", "oak sign", "oak trapdoor", "oak wood", "observer", "obsidian", 
    "orange banner", "orange bed", "orange carpet", "orange concrete powder", "orange concrete", "orange glazed terracotta", 
    "orange shulker box", "orange stained glass pane", "orange stained glass", "orange terracotta", "orange tulip", 
    "orange wool", "oxeye daisy", 
    "packed ice", "peony", "petrified oak slab", "pink banner", "pink bed", "pink carpet", "pink concrete powder", 
    "pink concrete", "pink glazed terracotta", "pink shulker box", "pink stained glass pane", "pink stained glass", 
    "pink terracotta", "pink tulip", "pink wool", "piston", "player head", "podzol", "polished andesite slab", 
    "polished andesite stairs", "polished andesite", "polished diorite slab", "polished diorite stairs", "polished diorite", 
    "polished granite slab", "polished granite stairs", "polished granite", "poppy", "portal", "potted acacia sapling", 
    "potted allium", "potted azure bluet", "potted bamboo", "potted birch sapling", "potted blue orchid", 
    "potted brown mushroom", "potted brown mushroom", "potted cactus", "potted cornflower", "potted dandelion", 
    "potted dark oak sapling", "potted dead bush", "potted fern", "potted jungle sapling", "potted lily of the valley", 
    "potted oak sapling", "potted orange tulip", "potted oxeye daisy", "potted pink tulip", "potted poppy", 
    "potted red mushroom", "potted red tulip", "potted spruce sapling", "potted white tulip", "potted wither rose", 
    "powered rail", "prismarine brick slab", "prismarine brick stairs", "prismarine bricks", "prismarine slab", 
    "prismarine stairs", "prismarine wall", "prismarine", "pumpkin", "purple banner", "purple bed", "purple carpet", 
    "purple concrete powder", "purple concrete", "purple glazed terracotta", "purple shulker box", 
    "purple stained glass pane", "purple stained glass", "purple terracotta", "purple wool", "purpur block", 
    "purpur pillar", "purpur slab", "purpur stairs", 
    "quartz block", "quartz pillar", "quartz slab", "quartz stairs", 
    "rail", "red banner", "red bed", "red carpet", "red concrete powder", "red concrete", "red glazed terracotta", 
    "red mushroom block", "red mushroom", "red nether brick slab", "red nether brick stairs", "red nether brick wall", 
    "red nether bricks", "red sand", "red sandstone slab", "red sandstone stairs", "red sandstone wall", "red sandstone", 
    "red shulker box", "red stained glass pane", "red stained glass", "red terracotta", "red tulip", "red wool", 
    "redstone block", "redstone comparator", "redstone lamp", "redstone ore", "redstone repeater", "redstone torch", 
    "rose bush", 
    "sand", "sandstone slab", "sandstone stairs", "sandstone wall", "sandstone", "sea lantern", "sea pickle", "seagrass", 
    "shulker box", "skeleton skull", "slime block", "smithing table", "smoker", "smooth quartz slab", 
    "smooth quartz stairs", "smooth quartz", "smooth red sandstone slab", "smooth red sandstone stairs", 
    "smooth red sandstone", "smooth sandstone slab", "smooth sandstone stairs", "smooth sandstone", "smooth stone slab", 
    "smooth stone", "snow block", "snow", "soul sand", "spawner", "sponge", "spruce button", "spruce door", 
    "spruce fence gate", "spruce fence", "spruce leaves", "spruce log", "spruce planks", "spruce pressure plate", 
    "spruce sapling ", "spruce slab", "spruce stairs", "spruce sign", "spruce trapdoor", "spruce wood", "scaffolding", 
    "sticky piston", "stone brick slab", "stone brick stairs", "stone brick wall", "stone bricks", "stone button", 
    "stone pressure plate", "stone slab", "stone stairs", "stone", "stonecutted", "stripped acacia log", 
    "stripped acacia wood", "stripped birch log", "stripped birch wood", "stripped dark oak log", "stripped dark oak wood", 
    "stripped jungle log", "stripped jungle wood", "stripped oak log", "stripped oak wood", "stripped spruce log", 
    "stripped spruce wood", "sugar cane", "sunflower", "sweet berry bush", 
    "tall grass", "tall seagrass", "terracotta", "tnt", "torch", "trapped chest", "tripwire hook", "tripwire", 
    "tube coral block", "tube coral fan", "tube coral", "turtle egg", 
    "vines", 
    "water", "wet sponge", "white banner", "white bed", "white carpet", "white concrete powder", "white concrete", 
    "white glazed terracotta", "white shulker box", "white stained glass pane", "white stained glass", "white terracotta", 
    "white tulip", "white wool", "wither rose", "wither skeleton skull", 
    "yellow banner", "yellow bed", "yellow carpet", "yellow concrete powder", "yellow concrete", "yellow glazed terracotta", 
    "yellow shulker box", "yellow stained glass pane", "yellow stained glass", "yellow terracotta", "yellow wool", 
    "zombie head", ];

module.exports = mcBlock;