const mcItem = ["acacia boat", "apple", "armour stand", "arrow", 
    "baked potato", "banner pattern", "bat spawn egg", "beetroot seeds", "beetroot soup", "beetroot", "birch boat", 
    "black dye", "blaze powder", "blaze rod", "blaze spawn egg", "blue dye", "bone", "bone meal", "book", "book and quill", 
    "bottle o enchanting", "bow", "bowl", "bread", "brick", "brown dye", "bucket", "bucket of cod", "bucket of pufferfish", 
    "bucket of salmon", "bucket of tropical fish", 
    "carrot", "carrot on a stick", "cat spawn egg", "cave spider spawn egg", "chainmail boots", "chainmail chestplate", 
    "chainmail helmet", "chainmail leggings", "charcoal", "chicken spawn egg", "chorus fruit", "clay", "clock", 
    "cocoa beans", "coal", "cod spawn egg", "compass", "cooked chicken", "cooked cod", "cooked mutton", "cooked porkchop", 
    "cooked rabbit", "cooked salmon", "cookie", "cow spawn egg", "creeper spawn egg", "crossbow", "cyan dye", 
    "dark oak boat", "diamond", "diamond axe", "diamond boots", "diamond chestplate", "diamond helmet", "diamond hoe", 
    "diamond horse armour", "diamond leggings", "diamond pickaxe", "diamond shovel", "diamond sword", "dolphin spawn egg", 
    "donkey spawn egg", "dragon's breath", "dried kelp", "drowned spawn egg", 
    "egg", "elder guardian spawn egg", "elytra", "emerald", "empty map", "enchanted book", "enchanted golden apple", 
    "ender pearl", "end crystal", "enderman spawn egg", "endermite spawn egg", "evoker spawn egg", "eye of ender", 
    "feather", "fermented spider eye", "firework rocket", "firework star", "fire charge", "fishing rod", "flint", 
    "flint and steel", "fox spawn", 
    "ghast spawn egg", "ghast tear", "glass bottle", "glistering melon slice", "glowstne dust", "gold ingot", 
    "gold nugget", "golden apple", "golden axe", "golden boots", "golden carrot", "golden chestplate", "golden helmet", 
    "golden hoe", "golden horse armour", "golden leggings", "golden pickaxe", "golden shovel", "golden sword", "gray dye", 
    "green dye", "guardian spawn egg", "gunpowder", 
    "heart of the sea", "horse spawn egg", "husk spawn egg", 
    "ink sac", "iron axe", "iron boots", "iron chestplate", "iron helmet", "iron hoe", "iron horse armour", "iron ingot", 
    "iron leggings", "iron nugget", "iron pickaxe", "iron shovel", "iron sword", "item frame", 
    "jungle boat", 
    "kelp", "knowledge book", 
    "lapis lazuli", "lava bucket", "lead", "leather", "leather boots", "leather cap", "leather horse armour", 
    "leather pants", "leather tunic","light blue dye", "light gray dye", "lime dye", "lingering potion", "llama spawn egg", 
    "magenta dye", "magma cream", "magma cube spawn egg", "map", "melon seeds", "melon slice", "milk bucket", "minecart", 
    "minecart with chest", "minecart with command block",  "minecart with furnace", "minecart with hopper", 
    "minecart with tnt", "mooshroom spawn egg", "mule spawn egg", "mushroom stew", "music disc (ward)", "music disc (wait)", 
    "music disc (stal)", "music disc (mellohi)", "music disc (mall)", "music disc (far)", "music disc (chirp)", 
    "music disc (cat)", "music disc (blocks)", "music disc (13)", "music disc (11)", "music disc (strad)", 
    "name tag", "nautilus shell", "nether brick", "nether quartz", "nether star", "nether wart", 
    "oak boat", "ocelot spawn egg", "orange dye", 
    "painting", "panda spawn egg", "paper", "parrot spawn egg", "phantom membrane", "phantom spawn egg", "pig spawn egg", 
    "pillager spawn egg", "pink dye", "poisonous potato", "polar bear spawn egg", "potato", "potions", "popped chorus fruit", 
    "pufferfish", "pufferfish spawn egg", "pumpkin pie", "pumpkin seeds", "purple dye", "prismarine crystals", 
    "prismarine shard", 
    "rabbit hide", "rabbit spawn egg", "rabbit stew", "rabbit's foot", "ravager spawn egg", "raw beef", "raw chicken", 
    "raw cod", "raw mutton", "raw porkchop", "raw rabbit", "raw salmon", "red dye", "redstone dust", "rotten flesh", 
    "saddle", "salmon spawn egg", "scute", "shears", "sheep spawn egg", "shield", "shulker shell", "shulker spawn egg", 
    "silverfish spawn egg", "skeleton horse spawn egg", "skeleton spawn egg", "slimeball", "slime spawn egg", "snowball", 
    "spectral arrow", "spider eye", "spider spawn egg", "splash potion", "spruce boat", "squid spawn egg", "steak", "stick", 
    "stone axe", "stone hoe", "stone pickaxe", "stone shovel", "stone sword", "stray spawn egg", "string", "sugar", 
    "sugar cane", "suspicious stew", "sweet berries", 
    "tipped arrow", "totem of undying", "trader llama spawn egg", "trident", "tropical fish", "tropical fish spawn egg", 
    "turtle shell", "turtle spawn egg", 
    "vex spawn egg", "villager spawn egg", "vindicator spawn egg", 
    "wandering trader spawn egg", "water bucket", "wheat", "wheat seeds", "white dye", "witch spawn egg", "wither skeleton spawn egg", "wolf spawn egg", "wooden axe", "wooden hoe", "wooden pickaxe", "wooden shovel", "wooden sword", "written book", 
    "yellow dye", 
    "zombie horse spawn egg", "zombie pigman spawn egg", "zombie spawn egg", "zombie villager spawn egg",];

module.exports = mcItem;