const mcMob = ["bat", "blaze", 
"cat", "cave spider", "chicken", "chicken jockey", "cod", "cow", "creeper", 
"dolphin", "donkey", "drowned", 
"elder guardian", "ender dragon", "enderman", "endermite", "evoker",
"fox", 
"ghast", 
"husk", 
"iron golem", 
"llama", 
"magma cube", "mooshroom", "mule", 
"ocelot", 
"panda", "parrot", "phantom", "pig", "pillager", "polar bear", "pufferfish", 
"rabbit", "ravager", 
"salmon", "sheep", "shulker", "silverfish", "skeleton", "skeleton horse", "slime", "snow golem", "spider", "spider jockey", 
"squid", "stray", 
"trader llama", "tropical fish", "turtle", 
"vex", "vindicator", "villager", 
"wandering trader", "witch", "wither", "wither skeleton", "wolf", 
"zombie", "zombie pigman", ];

module.exports = mcMob;