const clan = ["Abyss", "Amber", "Aqua", "Ash", "Aurora", "Autumn", 
    "Birch", "Blizzard", "Blood", "Blue", "Breeze", "Brook", "Bush", 
    "Cloud", "Clover", "Cypress", 
    "Dawn", "Deer", "Dew", "Dove", "Dusk", 
    "Ember", 
    "Fall", "Feather", "Fire", "Flame", "Frost", 
    "Glacier", "Gorse", "Grass", "Grove", 
    "Hill", "Hollow", "Holly", 
    "Ice", "Ivy", 
    "Lake", "Leaf", "Lightning", 
    "Marsh", "Mist", "Misty", "Moon", "Moss", "Mountain", "Mud", 
    "Night", 
    "Oak", "Ocean", "Orchard", "Orchid", 
    "Pebble", "Petal", "Pine", 
    "Rain", "Reed", "River", 
    "Sand", "Sea", "Shade", "Shadow", "Sky", "Smoke", "Snow", "Spring", "Stone", "Storm", "Stream", "Summer", "Sun", "Swift", 
    "Thorn", "Thunder", "Trout", 
    "Willow", "Wind", "Winter", 
    "Yellow", ];

module.exports = clan;