const coatColour = ["albino", "almond", "amber", "auburn", "ashen",
    "beige", "black", "blue", "blue-gray", "brass", "bronze", "brown", 
    "caramel", "cedar", "cherry", "chestnut", "chocolate", "cinnamon", "cocoa", "copper", "cream", 
    "dark-brown", "dark-gray", "dark-orange", "dark-red", "dove-gray", 
    "ebony", 
    "fawn", "fiery", "flame", "frost", 
    "ginger", "gold", "golden", "gray", 
    "honey", 
    "jet", 
    "lilac", "light-brown", "light-gray", 
    "mahogany", "maroon", "mauve", "milk", 
    "obsidian", "olive", "onyx", 
    "pale", "peach", "pearl", 
    "raven", "red", "reddish-brown", "russet", "rust", 
    "sandy", "silver", "silver-gray", "snow", "stone", "sunset",
    "tan", "tawny",
    "vanilla", 
    "white",
    "yellow"];

module.exports = coatColour;