const prefix = ["Acorn", "Adder", "Alder", "Amber", "Ant", "Apple", "Apricot", "Arch", "Ash", "Aspen", "Aster", "Avocet", 
    "Badger", "Balsam", "Basil", "Bark", "Barley", "Bat", "Bear", "Beaver", "Bee", "Beach", "Beech", "Beetle", "Berry", "Birch", "Bird", "Black", "Blade", "Blaze", "Blazing", "Blind", "Blizzard", "Bloom", "Blood", "Blossom", "Blue", "Bluebell", "Bone", "Boulder", "Bounce", "Bracken", "Bramble", "Branch", "Brave", "Breeze", "Briar", "Bright", "Brindle", "Bristle", "Broken", "Brook", "Brown", "Brush", "Bubbling", "Buck", "Bumble", "Burnet", "Buzzard", 
    "Cedar", "Cheetah", "Cherry", "Chestnut", "Chick", "Chirp", "Chive", "Chub", "Cinder", "Claw", "Clay", "Clear", "Cloud", "Clouded", "Cloudy", "Clover", "Coal", "Cold", "Comfrey", "Cone", "Coot", "Copper", "Coral", "Corn", "Cougar", "Crane", "Creek", "Cricket", "Crooked", "Crouch", "Crow", "Cuckoo", "Crystal", "Curl", "Curlew", "Curly", "Cypress", 
    "Dace", "Daffodil", "Daisy", "Dandelion", "Dandy", "Dapple", "Dappled", "Dark", "Dawn", "Dead", "Deer", "Dew", "Dewy", "Dirt", "Distant", "Dock", "Doe", "Dove", "Drift", "Drizzle", "Duck", "Dusk", "Dust", "Dusty", 
    "Eagle", "Ebony", "Echo", "Eel", "Egg", "Elm", "Ember", "Evening", 
    "Falcon", "Fallen", "Fallow", "Fawn", "Feather", "Fennel", "Fern", "Ferret", "Fidget", "Fin", "Finch", "Fire", "Fish", "Flail", "Flame", "Flash", "Flax", "Flech", "Fleet", "Flint", "Flower", "Fluffy", "Fly", "Fog", "Foggy", "Forest", "Fossil", "Fox", "Freckle", "Frog", "Frond", "Frost", "Furze", "Fuzzy", 
    "Gale", "Gannet", "Gar", "Gay", "Gem", "Ginger", "Glade", "Gold", "Golden", "Goose", "Gorge", "Gorse", "Gray", "Grass", "Gravel", "Green", "Grouse", "Gull", 
    "Hail", "Half", "Hare", "Hatch", "Haven", "Hawk", "Hay", "Hazel", "Heather", "Heavy", "Heron", "Hickory", "Hollow", "Holly", "Honey", "Hoot", "Hop", "Horse", "Hot", "Hound", 
    "Ice", "Ivy", 
    "Jagged", "Jaguar", "Jasmine", "Jay", "Jet", "Jump", "Juniper", 
    "Kestrel", "Kink", 
    "Lake", "Lamb", "Larch", "Lark", "Lavender", "Leaf", "Leech", "Lemon", "Leopard", "Lichen", "Light", "Lightning", "Lilac", "Lily", "Lion", "Little", "Lizard", "Log", "Long", "Lost", "Loud", "Low", "Lynx", 
    "Maggot", "Magpie", "Mallow", "Maple", "Marigold", "Marsh", "Meadow", "Midge", "Milk", "Mink", "Minnow", "Mint", "Mist", "Mistle", "Misty", "Mole", "Moon", "Morning", "Moss", "Mossy", "Mosquito", "Moth", "Mottle", "Mouse", "Mud", "Muddy", "Mumble", "Mushroom", 
    "Nectar", "Needle", "Nettle", "Newt", "Night", "Nut", 
    "Oak", "Oat", "Odd", "Olive", "One", "Onion", "Otter", "Owl", 
    "Pale", "Panther", "Parsley", "Parsnip", "Patch", "Pear", "Pebble", "Pepper", "Perch", "Petal", "Pheasant", "Pigeon", "Pike", "Pine", "Plum", "Poppy", "Pounce", "Pool", "Prickle", "Primrose", "Puddle", "Pumpkin", 
    "Quail", "Quick", "Quiet", 
    "Rabbit", "Ragged", "Raccoon", "Rain", "Raspberry", "Rat", "Raven", "Red", "Reed", "Ripple", "River", "Robin", "Rock", "Rook", "Rose", "Rowan", "Rubble", "Ruin", "Rue", "Running", "Rush", "Russet", "Rust", "Rusty", "Rye",  
    "Sage", "Sand", "Sandy", "Sap", "Scorch", "Sea", "Sedge", "Seed", "Shade", "Shadow", "Sharp", "Sheep", "Shell", "Shimmer", "Shining", "Short", "Shrew", "Shred", "Silver", "Sky", "Slate", "Sleek", "Slight", "Sloe", "Slow", "Smoke", "Small", "Snail", "Snake", "Snap", "Sneeze", "Snip", "Snook", "Snow", "Soft", "Song", "Soot", "Sorrel", "Spark", "Sparrow", "Speckle", "Spider", "Spike", "Splash", "Spot", "Spotted", "Spruce", "Squirrel", "Stag", "Starling", "Stem", "Stoat", "Stone", "Storm", "Strike", "Stumpy", "Sun", "Sunny", "Swallow", "Swan", "Sweet", "Swift", 
    "Tall", "Talon", "Tangle", "Tansy", "Tawny", "Thistle", "Thorn", "Thrift", "Thrush", "Thunder", "Tiger", "Timber", "Tiny", "Toad", "Torn", "Torrent", "Trout", "Tumble", "Turkey", "Turtle", "Twig", "Twilight", 
    "Vine", "Violet", "Vixen", "Vole", "Vulture", 
    "Wasp", "Wave", "Weasel", "Web", "Weed", "Wet", "Whisker", "White", "Whorl", "Wild", "Willow", "Wind", "Wolf", "Wood", "Wooly", "Wren", 
    "Yarrow", "Yellow"];

module.exports = prefix;