const suffix = ["acorn", "ash", 
    "back", "bark", "bee", "bell", "belly", "berry", "bird", "blaze", "bounce", "branch", "breeze", "briar", "bright", "brook", "burr", "bush", 
    "call", "catcher", "claw", "cloud", "coat", "creek", "crystal", "cry", 
    "dapple", "dawn", "dream", "dust", 
    "ear", "eye", "eyes", 
    "face", "fall", "fang", "feather", "fern", "fin", "fire", "fish", "flame", "flank", "flash", "fleck", "flight", "flower", "fluff", "flurry", "foot", "frost", "fur", 
    "gaze", "gem", "gleam", "glisten", "glow", "goose", "gorse", "grass", 
    "hare", "hawk", "haze", "heart", "heather", "hollow", "holly", 
    "ice", "ivy", 
    "jaw", "jay", "jump", 
    "leaf", "leap", "leg", "light", 
    "mask", "mist", "moon", "mouse", "muzzle", 
    "nettle", "night", "nose", 
    "ocean", 
    "pad", "patch", "path", "pearl", "pelt", "petal", "pond", "pool", "poppy", "pounce", "puddle", 
    "ripple", "river", "rock", "run", "runner", 
    "scar", "sea", "seed", "shade", "shadow", "sheen", "shimmer", "shine", "sight", "skip", "sky", "slip", "snout", "snow", "soar", "song", "spark", "speck", "speckle", "spiral", "spirit", "splash", "spots", "spring", "stalk", "stem", "step", "sting", "stone", "storm", "streak", "stream", "stride", "strike", "stripe", "sun", "swipe", "swirl", 
    "tail", "talon", "thicket", "thistle", "thorn", "throat", "tip", "toe", "tooth", "tree", "tuft", "tumble", 
    "vine", 
    "watcher", "water", "whisker", "willow", "wind", "wing", "wish", "whisper"];

module.exports = suffix;