const tribe = ["Acorn That Falls From Tree", 
    "Bee That Buzzes in Flowers", 
    "Berry That Grows on Bush", 
    "Branch That Falls From Tree", "Branch Where Small Owl Sits", 
    "Breeze That Comes From North", "Breeze That Comes From East", "Breeze That Comes From South", "Breeze That Comes From West", 
    "Brook Where Small Fish Swim", 
    "Butterfly That Dances in Sky", 
    "Cave Where Flying Mice Live", 
    "Cedar That Rustles in Breeze", 
    "Cloud That Floats in Sky", 
    "Cougar That Stalks in Shadows", 
    "Creek Where Small Fish Swim", 
    "Dandelion That Waves in Wind", 
    "Dog That Barks at Night", "Dog That Barks in Morning", 
    "Dove That Floats on Air", 
    "Duck That Swims in Pond", 
    "Eagle That Soars Through Sky", 
    "Flint That Shines From Rock", 
    "Flower On Edge of River", "Flower That Faces East", "Flower That Grows From Rock", 
    "Fox That Walks Through Meadow", 
    "Frog That Croaks at Night", "Frog That Leaps on Lilypads", 
    "Grass Where Small Mice Hide", "Grass Where Small Mice Sleep", 
    "Hare That Hides From Cats", "Hare That Sleeps in Bush", 
    "Hill Where Big Cats Live", 
    "Heron That Sits in Lake", 
    "Leaf That Grows in Spring", "Leaf That Falls From Tree", "Leaf That Turns New Colour", 
    "Lilypad That Sits in Lake", 
    "Mouse That Hides from Cats", 
    "Moth That Flies Towards Light", 
    "Petals That Bloom in Sunlight", 
    "Rain That Falls on River", "Rain That Falls on Ridge", "Rain That Falls on Mountain", "Rain That Falls on Lake", 
    "Ripple That Forms on Lake", "Ripple That Forms on River", 
    "Rock That Falls From Mountain", "Rock That Falls From Crag", "Rock Where Small Mice Hide", "Rock Where Small Birds Hide", 
    "Salmon That Swims in Lake", 
    "Sand That Waves Lap At", 
    "Sun That Shines on Lake", "Sun That Shines on Mountain", "Sun That Shines on River", "Sun That Shines on Tree", "Sun That Shines After Rain", "Sun That Shines Through Clouds", 
    "Sunflower That Stares at Light", 
    "Sky That Sits on Earth", "Sky Where Lone Heron Flies", "Sky Where Lone Eagle Flies", "Sky Where Lone Hawk Flies", 
    "Snake That Bears Shining Scales", 
    "Stag That Stands in Shadows", 
    "Stream That Creeps Through Trees",
    "Squirrel That Runs Up Tree", 
    "Toad That Croaks and Jumps", 
    "Tree That Grows from Rock", "Tree That Hides the Sky", "Tree That Rests on Earth", "Tree That Sways in Wind", "Tree That Touches the Sky", "Tree Where Small Birds Hide", "Tree Where Small Birds Sleep", 
    "Trout That Swims Up River", 
    "Tulip That Rustles in Breeze", 
    "Turtle That Hides In Shell", 
    "Willow That Whispers in Wind", ];

module.exports = tribe;